### ISSUE TITLE
DStream segmentation fault on sensor dataset

### ISSUE THREAD

**Issue by wzru** [intellistream/Sesame#167]
## params
lambda: 0.998
beta: 0.1
cm: 4
cl: 0.2
grid_width: 200 

## error message
```bash
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 49) >= this->size() (which is 41)
```

**Comment by tuidan** [comment]
param2:
 : join.new lambda 0.998 \
 : join.new beta 0.001 \
 : join.new cm 1 \
 : join.new cl 0.7 \
 : join.new grid_width 50 \
 : join.run run.sesame

param3:
 : join.new lambda 0.998 \
 : join.new beta 0.1 \
 : join.new cm 3 \
 : join.new cl 0.2 \
 : join.new grid_width 0.5 \

**Comment by wzru** [comment]
Params below still occurs segmentation fault:
    : join.new algo 6 \
    : join.new lambda 0.998 \
    : join.new beta 0.1 \
    : join.new cm 3 \
    : join.new cl 1 \
    : join.new grid_width 200 \
    : join.run run.sesame
